### ISSUE TITLE
ProRender not installing on Unreal Engine 4.23 

### ISSUE THREAD

**Issue by OnlyOnePro** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUE#1]
Edit: I put the wrong version in the Issue Title. It isn't working on 4.24, not 4.23 (Sorry about that) 

I tried to install the official plug-in, but the engine doesn't installs it. It tells me to compile the project from the source. When I open Visual Studio (2019 16.5.4 Community Edition with the proper toolset for Unreal Engine and Cpp development), the build output throws the following line:

`2>UnrealBuildTool: error : Could not find definition for module 'RPRPPluginVersion', (referenced via DummyProject.uproject -> RPRPlugin.uplugin)`

The project is a scratch one created just for this. It compiles successfully prior to the addition of the plug-in.

**Comment by feniksa** [comment]
Hi @OnlyOnePro . Thank you for reporting issue.

Please, can you try latest build for UE 4.24: https://drive.google.com/open?id=1gbXM4ciNQ2CB5apB7AX3vsat2u5FZB5o

Steps to install:

1. Download latest build (link above)
2. Open directory with your UE4.24 project (for example: c:/assets/hello_world)
3. Put zip archive content into c:/assets/hello_world

Directory structure example: https://imgur.com/a/9O1vt9I

Thank you

**Comment by OnlyOnePro** [comment]
It works! Thanks! I tried later with the old plug-in copying it to that same destination and with the same folder structure, but it wasn't working.
What you guys did fixed it. Thanks a lot!

**Comment by bsavery** [comment]
Thanks.  We're merging fixes now.  You can also build from source at https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUE/tree/develop to get the latest and greatest if you have the ability to compile things.

**Comment by feniksa** [comment]
Native build for UE 4.23 can be found here: https://200volts.com/cloud/index.php/s/K7ack2taA6ropJX
