### ISSUE TITLE
Will this plugin work on 4.25?

### ISSUE THREAD

**Issue by corneel** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUE#12]
Is it possible for me to compile and use this plugin on 4.25 of Unreal Engine?

Thanks.
Corneel.

**Comment by feniksa** [comment]
Hi @corneel ,

Unreal plugin compiles and run on UE 4.25 engine. To compile plugin for UE 4.25:

1. Right click on RPR.uproject -> Switch unreal version. Select UE 4.25
2. If everything ok, Open generated sln file in Visual Studio
3. Compile
4. Run (just click F5 in VS

---
Unfortunately automated scripts like BuildPluginTools/BuildPlugin/Build_RPRPlugin_424.bat doesn't work, only manual build.
![image](https://user-images.githubusercontent.com/379911/95024807-2329d980-068e-11eb-8cff-b13c774e6ba8.png)

Thanks
